name: Trigger auto deployment for v2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/v2-AutoDeployTrigger-4db6dce8-e508-4f8b-b11e-e1265ec33ef5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.V2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.V2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.V2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: workv2.azurecr.io
          registryUsername: ${{ secrets.V2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.V2_REGISTRY_PASSWORD }}
          containerAppName: v2
          resourceGroup: anicole-e2
          imageToBuild: workv2.azurecr.io/v2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


